name: Lighthouse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://paulinha.com.br/
            https://paulinha.com.br/planos
            https://paulinha.com.br/pagamento
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './.lighthouserc.json'
          runs: 3
          budgetPath: './.lighthouse/budget.json'
